"use client";

import { useState } from "react";
import { FileText, Download, Share2, Copy, Check } from "lucide-react";
import { cleanText } from "@/lib/text";

export function DocumentChecklist({ schemeName, documentsMd }: { schemeName: string; documentsMd?: string }) {
  const [copiedSms, setCopiedSms] = useState(false);
  const [copiedWa, setCopiedWa] = useState(false);
  const [checkedItems, setCheckedItems] = useState<Record<number, boolean>>({});

  if (!documentsMd || documentsMd.trim() === "") {
    return (
      <div className="bg-white rounded-2xl border border-neutral-200 p-5 mb-4">
        <div className="flex items-center gap-2 mb-4 pb-3 border-b border-neutral-100">
          <FileText size={16} className="text-saffron" />
          <h2 className="font-bold text-neutral-800">Documents Required</h2>
          <span className="text-xs text-neutral-400" style={{ fontFamily: "var(--font-devanagari), serif" }}>· आवश्यक दस्तावेज़</span>
        </div>
        <p className="text-sm text-neutral-600">
          Document requirements require manual verification.
        </p>
      </div>
    );
  }

  // Parse documents markdown into an array of items
  const lines = cleanText(documentsMd).split("\n").filter(l => l.trim() !== "");
  const checklistItems = lines
    .map(l => l.replace(/^[-*#]+\s*/, "").trim())
    .filter(l => l.length > 3);

  const smsText = `Eligible Scheme: ${schemeName}
Documents Needed:
${checklistItems.map((item, i) => `${checkedItems[i] ? '✓' : '✗'} ${item}`).join('\n')}

Generated by Suvidha Setu`;

  const waText = `*Eligible Scheme:* ${schemeName}
*Documents Needed:*
${checklistItems.map((item, i) => `${checkedItems[i] ? '✓' : '✗'} ${item}`).join('\n')}

_Generated by Suvidha Setu_`;

  const copySms = () => {
    navigator.clipboard.writeText(smsText);
    setCopiedSms(true);
    setTimeout(() => setCopiedSms(false), 2000);
  };

  const copyWa = () => {
    navigator.clipboard.writeText(waText);
    setCopiedWa(true);
    setTimeout(() => setCopiedWa(false), 2000);
  };

  const downloadPdf = () => {
    window.print();
  };

  const toggleCheck = (index: number) => {
    setCheckedItems(prev => ({ ...prev, [index]: !prev[index] }));
  };

  const readinessScore = checklistItems.length > 0 
    ? Math.round((Object.values(checkedItems).filter(Boolean).length / checklistItems.length) * 100)
    : 0;

  return (
    <div className="bg-white rounded-2xl border border-neutral-200 p-5 mb-4 print:border-none print:shadow-none">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4 pb-3 border-b border-neutral-100 print:border-b-2 print:border-neutral-800">
        <div className="flex items-center gap-2">
          <FileText size={16} className="text-saffron print:text-black" />
          <h2 className="font-bold text-neutral-800 text-lg">Documents Required</h2>
          <span className="text-xs text-neutral-400 print:hidden" style={{ fontFamily: "var(--font-devanagari), serif" }}>· आवश्यक दस्तावेज़</span>
        </div>

        <div className="flex flex-wrap items-center gap-2 print:hidden">
          <button
            onClick={copySms}
            className="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-lg border border-neutral-200 text-neutral-600 hover:bg-neutral-50 transition-colors"
          >
            {copiedSms ? <Check size={14} className="text-india-green" /> : <Copy size={14} />}
            Copy SMS
          </button>
          <button
            onClick={copyWa}
            className="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-lg bg-green-50 text-green-700 hover:bg-green-100 transition-colors"
          >
            {copiedWa ? <Check size={14} /> : <Share2 size={14} />}
            Copy WhatsApp
          </button>
          <button
            onClick={downloadPdf}
            className="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-lg bg-saffron text-white hover:bg-saffron-dark transition-colors"
          >
            <Download size={14} />
            Download PDF
          </button>
        </div>
      </div>

      <div className="space-y-3 print:space-y-4">
        <div className="flex items-center justify-between mb-4 bg-neutral-50 px-3 py-2 rounded-lg border border-neutral-100 print:hidden">
          <span className="text-sm font-semibold text-neutral-700">Readiness Score</span>
          <span className="text-sm font-bold text-saffron-dark">{readinessScore}%</span>
        </div>
        
        <p className="hidden print:block text-xs text-neutral-500 uppercase tracking-widest font-semibold mb-4">
          Suvidha Setu Checklist for: {schemeName}
        </p>

        {checklistItems.map((item, i) => (
          <div 
            key={i} 
            className="flex items-start gap-3 group cursor-pointer"
            onClick={() => toggleCheck(i)}
          >
            <div className={`w-5 h-5 rounded border mt-0.5 flex-shrink-0 flex items-center justify-center transition-colors print:border-neutral-500 print:border-2 ${checkedItems[i] ? 'bg-india-green border-india-green' : 'border-neutral-300'}`}>
              {checkedItems[i] && <Check size={14} className="text-white print:text-black" />}
            </div>
            <p className={`text-sm print:text-black print:text-base transition-colors ${checkedItems[i] ? 'text-neutral-400 line-through print:no-underline print:text-black' : 'text-neutral-700'}`}>
              {item}
            </p>
          </div>
        ))}
        
        <div className="hidden print:block mt-8 pt-4 border-t border-neutral-200">
          <p className="text-xs text-neutral-500">Generated on {new Date().toLocaleDateString()} | Language: English</p>
        </div>
      </div>
    </div>
  );
}
